title: Tom치코 Mikula
subtitle: UI/UX designer @ INGAME STUDIOS
description: >
  Game Designer & UI/UX Specialist with a PhD in Computer Science. I combine cognitive psychology and data-driven design to create intuitive game experiences. I collaborate on feature design and translate ideas into polished, player-focused UI/UX for shipped titles. Passionate about clear design direction and delivering cohesive player experiences.
author: Tom치코 Mikula

email: mail@tomasmikula.cz
office: "5.070"
office-hours: after e-mail consulation


types: [course, summer, winter]
courses: [PDS, PAPR1, JP]

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

sass:
  style: compressed

# exclude:
#   - Gemfile
#   - Gemfile.lock

name: Jekyll Actions
uses: helaili/jekyll-action@2.1.0
